### PR TITLE
Make app constructor protected for tests

### PR DESCRIPTION
**Pull request by jabrah**
Not captured in the ITs ticket (https://github.com/eclipse-pass/main/issues/248), but now necessary to get ITs in this repo to work

### CODE REVIEW

**Review by markpatton — COMMENTED** [review]
ITs do not pass for me. I'm using Java 8.

I get failures like:
```
testWhitelistFilter(org.dataconservancy.pass.notification.dispatch.impl.email.EmailDispatchImplIT)  Time elapsed: 0.189 se
c  <<< ERROR!
java.lang.RuntimeException: javax.mail.MessagingException: Certificates do not conform to algorithm constraints;
  nested exception is:
        javax.net.ssl.SSLHandshakeException: Certificates do not conform to algorithm constraints
        at sun.security.provider.certpath.AlgorithmChecker.check(AlgorithmChecker.java:237)
        at sun.security.ssl.AbstractTrustManagerWrapper.checkAlgorithmConstraints(SSLContextImpl.java:1423)
        at sun.security.ssl.AbstractTrustManagerWrapper.checkAdditionalTrust(SSLContextImpl.java:1352)
        at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1296)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
        at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:377)
        at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
        at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:152)
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1397)
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1305)
       at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
        at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:626)
        at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:400)
        at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:238)
        at com.sun.mail.iap.Protocol.<init>(Protocol.java:134)
        at com.sun.mail.imap.protocol.IMAPProtocol.<init>(IMAPProtocol.java:131)
        at com.sun.mail.imap.IMAPStore.newIMAPProtocol(IMAPStore.java:763)
        at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:698)
        at javax.mail.Service.connect(Service.java:366)
        at javax.mail.Service.connect(Service.java:246)
        at org.dataconservancy.pass.notification.SimpleImapClientFactory.getObject(SimpleImapClientFactory.java:81)
        at org.dataconservancy.pass.notification.dispatch.impl.email.EmailDispatchImplIT.setUp(EmailDispatchImplIT.java:126)
```

**Comment by jabrah** [comment]
Interestingly, I don't see those certs errors, but I do get some other error messages. The ones I get don't fail the IT runs.

No idea if there's an environment difference that would cause a difference in behavior, i'm running:

```
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: /opt/maven
Java version: 1.8.0_312, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.10.102.1-microsoft-standard-wsl2", arch: "amd64", family: "unix"

Docker for WIndows: v4.7.1
Docker Engine: 20.10.14
```

### Message:
```
08:45:39.949 [main] WARN  [LoggingAspect] - FAILED dispatching notification to [mailto:moo-thru@bar.edu], cc [] bcc [] (Notification type: SUBMISSION_APPROVAL_INVITE, Event URI: http://pass.example.com/fcrepo/rest/submissionEvents/xyz/890, Resource URI: http://pass.example.com/fcrepo/rest/submissions/abc/123)
org.dataconservancy.pass.notification.dispatch.DispatchException: Third party error
        at org.dataconservancy.pass.notification.dispatch.impl.email.EmailDispatchImpl.dispatch(EmailDispatchImpl.java:104)
        at org.dataconservancy.pass.notification.dispatch.impl.email.EmailDispatchImpl$$FastClassBySpringCGLIB$$eb24defd.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:55)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
        at org.dataconservancy.pass.notification.dispatch.impl.email.EmailDispatchImpl$$EnhancerBySpringCGLIB$$de5b1727.dispatch(<generated>)
        at org.dataconservancy.pass.notification.dispatch.impl.email.EmailDispatchImplIT.nonExistentEmailAddress(EmailDispatchImplIT.java:363)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
        at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
        at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
        at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: org.simplejavamail.mailer.internal.mailsender.MailSenderException: Third party error
        at org.simplejavamail.mailer.internal.mailsender.MailSender.sendMailClosure(MailSender.java:283)
        at org.simplejavamail.mailer.internal.mailsender.MailSender.send(MailSender.java:211)
        at org.simplejavamail.mailer.Mailer.sendMail(Mailer.java:239)
        at org.simplejavamail.mailer.Mailer.sendMail(Mailer.java:230)
        at org.dataconservancy.pass.notification.dispatch.impl.email.EmailDispatchImpl.dispatch(EmailDispatchImpl.java:96)
        ... 49 common frames omitted
Caused by: javax.mail.SendFailedException: Invalid Addresses
        at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:2079)
        at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1301)
        at org.simplejavamail.mailer.internal.mailsender.MailSender.sendMailClosure(MailSender.java:266)
        ... 53 common frames omitted
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 554 5.7.1 <moo-thru@bar.edu>: Relay access denied

        at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1979)
        ... 55 common frames omitted
08:45:39.968 [main] INFO  [EmailComposer] - Whitelisted recipients: [staffWithNoGrants@jhu.edu]
08:45:40.995 [main] INFO  [LoggingAspect] - Successfully dispatched notification with id <95699736.19.1654692339969@BahkPC-Home.localdomain> to [mailto:staffWithNoGrants@jhu.edu], cc [facultyWithGrants@jhu.edu] bcc [] (Notification type: SUBMISSION_APPROVAL_INVITE, Event URI: http://pass.example.com/fcrepo/rest/submissionEvents/xyz/890, Resource URI: http://pass.example.com/fcrepo/rest/submissions/abc/123)
```

**Comment by markpatton** [comment]
I note that the ITs run by GH are passing. Perhaps that's good enough to merge even with local issues?

**Comment by jabrah** [comment]
I'd be fine either way. It would be nice to eventually know what changes to environments would cause the tests to fail like this, though, since I imagine other people may encounter the issue.

**Comment by markpatton** [comment]
Should be fixed by #87

**Pull request closed without merging**
